#!/bin/make -f
# SPDX-License-Identifier: GPL-2.0+
# Copyright (c) Meta Platforms, Inc. and affiliates.

obj-m += glath06a-64o-cpld.o
glath06a-64o-cpld-objs := glath06a-64o-cpld-i2c.o ../lib/regbit-sysfs.o ../lib/smb-cpld-i2c.o
