#!/bin/make -f
# SPDX-License-Identifier: GPL-2.0+
# Copyright (c) Meta Platforms, Inc. and affiliates.

obj-m += dsf-fan-cpld.o
obj-m += decker-cpld.o
obj-m += meru-vcpld.o
decker-cpld-objs := decker-cpld-i2c.o ../lib/regbit-sysfs.o
meru-vcpld-objs := meru-vcpld-i2c.o
