#!/bin/make -f
# SPDX-License-Identifier: GPL-2.0+
# Copyright (c) Meta Platforms, Inc. and affiliates.

obj-m += scd-watchdog-darwin.o
obj-m += amax5970.o
obj-m += aslg4f4527.o
obj-m += blackhawk-cpld.o
blackhawk-cpld-objs := blackhawk-cpld-i2c.o ../lib/regbit-sysfs.o
obj-m += rook-fan-cpld.o
