#!/bin/make -f
# SPDX-License-Identifier: GPL-2.0+
# Copyright (c) Meta Platforms, Inc. and affiliates.

obj-m += glath05a-64o-cpld.o
glath05a-64o-cpld-objs := glath05a-64o-cpld-i2c.o ../lib/regbit-sysfs.o ../lib/smb-cpld-i2c.o
obj-m += glath05a-64o-fan-cpld.o
glath05a-64o-fan-cpld-objs := glath05a-64o-fan-cpld-i2c.o ../lib/fan-cpld-i2c.o
