#!/bin/make -f
# SPDX-License-Identifier: GPL-2.0+
# Copyright (c) Meta Platforms, Inc. and affiliates.

obj-m += quicksilver-cpld.o
quicksilver-cpld-objs := quicksilver-cpld-i2c.o ../lib/regbit-sysfs.o
