#!/bin/make -f
# SPDX-License-Identifier: GPL-2.0+
# Copyright (c) Meta Platforms, Inc. and affiliates.

obj-m += bp4a_isl68137.o
obj-m += bp4a_lm90.o
obj-m += bp4a_max1363.o
ifndef CONFIG_LEDS_TRIGGER_TIMER
obj-m += ledtrig-timer.o
endif
