name: Secret Scanner (go/secret-scanner)
on:
  push:
    branches:
      - main
    paths:
      - '.arista/secret_allowlist.yaml'
  pull_request:
  # Uncomment this if you would like the optional verification function
  # issue_comment:
  #   types: 
  #     - created
jobs:
  secret-scanner:
    runs-on: self-hosted
    steps: 
      - name: Run scanner
        uses: aristanetworks/secret-scanner-service@v2
