name: Automatically Update Platform Configs on Change

on:
  push:
    paths:
      - 'arista/util/configs-and-diagrams/GenerateConfigsAndDiagrams/BaseConfigs.py'
      - 'arista/util/configs-and-diagrams/GenerateConfigsAndDiagrams/Platforms/**'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install diagrams

    - name: Update JSON configs for all platforms
      run: |
        cd arista/util/configs-and-diagrams
        python generate.py --update_all_configs

        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        git add ../../../fboss/platform/configs/*

        if git diff --cached --quiet; then
          echo "No changes to commit. Exiting..."
          exit 0
        fi

        git commit -m "Automatically update all JSON configs"
        git push