on: 
  workflow_dispatch:

name: Upstream Sync Manual

jobs:
  run_sample_script:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check-out latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.GIT_PRIVATE_KEY }}
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Run Bash script
        env:
          GH_TOKEN: ${{ secrets.SRV_FBOSS_ARISTA_ROBOT_TOKEN }}
        run: ./arista-ci-scripts/upstream_sync.sh
      - name: Send status email
        if: success() || failure()
        run: |
          mail_to="arajeev@arista.com"
          subject=$(cat status_email_subject.txt)
          body_text_file="status_email_content.txt"
          attachment_path="upstream_sync_status.txt"
          ./arista-ci-scripts/mailer.py --mail_to="$mail_to" --subject="$subject" --body_text_file="$body_text_file" --attachment_path="$attachment_path" --sender_mail_id="${{ secrets.GMAIL_USERNAME }}" --sender_mail_password="${{ secrets.GMAIL_PASSWORD }}"
        shell: bash
